//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTV3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMARTV3.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Strength (Current):.
        /// </summary>
        public static string actualStrength {
            get {
                return ResourceManager.GetString("actualStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        public static string ammo {
            get {
                return ResourceManager.GetString("ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APS.
        /// </summary>
        public static string aps {
            get {
                return ResourceManager.GetString("aps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bde/Flt/Wg:.
        /// </summary>
        public static string brigade {
            get {
                return ResourceManager.GetString("brigade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability Code:.
        /// </summary>
        public static string capability {
            get {
                return ResourceManager.GetString("capability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Category: .
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caveats:.
        /// </summary>
        public static string caveats {
            get {
                return ResourceManager.GetString("caveats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 1 - Combat Rations:.
        /// </summary>
        public static string class1 {
            get {
                return ResourceManager.GetString("class1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 2 - Personal Equipment and Uniforms:.
        /// </summary>
        public static string class2 {
            get {
                return ResourceManager.GetString("class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 3 - Petroleum, Oils, Lubricants:.
        /// </summary>
        public static string class3 {
            get {
                return ResourceManager.GetString("class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 5 - Ammunition:.
        /// </summary>
        public static string class5 {
            get {
                return ResourceManager.GetString("class5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 7 - Spare Parts:.
        /// </summary>
        public static string class7 {
            get {
                return ResourceManager.GetString("class7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Vehicle/Vessel/Aircraft Serviceability Rate:.
        /// </summary>
        public static string combatVehicle {
            get {
                return ResourceManager.GetString("combatVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comms.
        /// </summary>
        public static string comms {
            get {
                return ResourceManager.GetString("comms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications Equipment Serviceability Rate:.
        /// </summary>
        public static string commsEquip {
            get {
                return ResourceManager.GetString("commsEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conplan: .
        /// </summary>
        public static string conplan {
            get {
                return ResourceManager.GetString("conplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Override Readiness Status:.
        /// </summary>
        public static string coStatus {
            get {
                return ResourceManager.GetString("coStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREVAL (OPRED Declaration):.
        /// </summary>
        public static string creval {
            get {
                return ResourceManager.GetString("creval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string crevalDate {
            get {
                return ResourceManager.GetString("crevalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dental.
        /// </summary>
        public static string dental {
            get {
                return ResourceManager.GetString("dental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed:.
        /// </summary>
        public static string deployed {
            get {
                return ResourceManager.GetString("deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed:.
        /// </summary>
        public static string deployedStatus {
            get {
                return ResourceManager.GetString("deployedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designated Strength (Declared):.
        /// </summary>
        public static string designatedStrength {
            get {
                return ResourceManager.GetString("designatedStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation:.
        /// </summary>
        public static string designation {
            get {
                return ResourceManager.GetString("designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div/Frm: .
        /// </summary>
        public static string division {
            get {
                return ResourceManager.GetString("division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echelon:.
        /// </summary>
        public static string echelon {
            get {
                return ResourceManager.GetString("echelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Readiness Status Remarks:.
        /// </summary>
        public static string equipmentComments {
            get {
                return ResourceManager.GetString("equipmentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readiness Status:.
        /// </summary>
        public static string equipmentStatus {
            get {
                return ResourceManager.GetString("equipmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FElm ID:.
        /// </summary>
        public static string felmId {
            get {
                return ResourceManager.GetString("felmId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FElm Name:.
        /// </summary>
        public static string felmName {
            get {
                return ResourceManager.GetString("felmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        public static string fitness {
            get {
                return ResourceManager.GetString("fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Generator:.
        /// </summary>
        public static string forceGen {
            get {
                return ResourceManager.GetString("forceGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP&amp;H:.
        /// </summary>
        public static string fph {
            get {
                return ResourceManager.GetString("fph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string fuel {
            get {
                return ResourceManager.GetString("fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFFG-20:.
        /// </summary>
        public static string iffg20 {
            get {
                return ResourceManager.GetString("iffg20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFFG-30:.
        /// </summary>
        public static string iffg30 {
            get {
                return ResourceManager.GetString("iffg30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFFG-45.
        /// </summary>
        public static string iffg45 {
            get {
                return ResourceManager.GetString("iffg45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB.
        /// </summary>
        public static string lob {
            get {
                return ResourceManager.GetString("lob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peacetime Location:.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt Duties.
        /// </summary>
        public static string ltDuties {
            get {
                return ResourceManager.GetString("ltDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Equip:.
        /// </summary>
        public static string majorEquip {
            get {
                return ResourceManager.GetString("majorEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        public static string medical {
            get {
                return ResourceManager.GetString("medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Deployment Plan:.
        /// </summary>
        public static string natDeploy {
            get {
                return ResourceManager.GetString("natDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Deloyment Plan Remarks:.
        /// </summary>
        public static string natDeployRem {
            get {
                return ResourceManager.GetString("natDeployRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Assessment:.
        /// </summary>
        public static string nationalAssessment {
            get {
                return ResourceManager.GetString("nationalAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eNRF/NRI:.
        /// </summary>
        public static string natoActive {
            get {
                return ResourceManager.GetString("natoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTM:.
        /// </summary>
        public static string ntm {
            get {
                return ResourceManager.GetString("ntm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation:.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Readiness Status Remarks:.
        /// </summary>
        public static string personnelComments {
            get {
                return ResourceManager.GetString("personnelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readiness Status:.
        /// </summary>
        public static string personnelStatus {
            get {
                return ResourceManager.GetString("personnelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE.
        /// </summary>
        public static string ppe {
            get {
                return ResourceManager.GetString("ppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected CREVAL (OPRED Declaration) Date:.
        /// </summary>
        public static string projectedCrevalDate {
            get {
                return ResourceManager.GetString("projectedCrevalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rations.
        /// </summary>
        public static string rations {
            get {
                return ResourceManager.GetString("rations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Readiness From:.
        /// </summary>
        public static string readinessFrom {
            get {
                return ResourceManager.GetString("readinessFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Readiness To:.
        /// </summary>
        public static string readinessTo {
            get {
                return ResourceManager.GetString("readinessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks:.
        /// </summary>
        public static string remarksGeneral {
            get {
                return ResourceManager.GetString("remarksGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service:.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare Parts.
        /// </summary>
        public static string spareParts {
            get {
                return ResourceManager.GetString("spareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized Equipment Serviceability Rate:.
        /// </summary>
        public static string specialEquip {
            get {
                return ResourceManager.GetString("specialEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp Equip.
        /// </summary>
        public static string spEquip {
            get {
                return ResourceManager.GetString("spEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMaRT Readiness Status:.
        /// </summary>
        public static string srStatus {
            get {
                return ResourceManager.GetString("srStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strat Lift Capacity:.
        /// </summary>
        public static string stratLiftCap {
            get {
                return ResourceManager.GetString("stratLiftCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strat Lift Rem:.
        /// </summary>
        public static string stratLiftRem {
            get {
                return ResourceManager.GetString("stratLiftRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subordinate Name:.
        /// </summary>
        public static string subunit {
            get {
                return ResourceManager.GetString("subunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Vehicle/Vessel/Aircraft Serviceability Rate:.
        /// </summary>
        public static string supportVehicle {
            get {
                return ResourceManager.GetString("supportVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainment Readiness Status Remarks:.
        /// </summary>
        public static string sustainmentComments {
            get {
                return ResourceManager.GetString("sustainmentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readiness Status:.
        /// </summary>
        public static string sustainmentStatus {
            get {
                return ResourceManager.GetString("sustainmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techs.
        /// </summary>
        public static string techs {
            get {
                return ResourceManager.GetString("techs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Readiness Status Remarks:.
        /// </summary>
        public static string trainingComments {
            get {
                return ResourceManager.GetString("trainingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readiness Status:.
        /// </summary>
        public static string trainingStatus {
            get {
                return ResourceManager.GetString("trainingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        public static string trAmmo {
            get {
                return ResourceManager.GetString("trAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip.
        /// </summary>
        public static string trEquip {
            get {
                return ResourceManager.GetString("trEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string trFuel {
            get {
                return ResourceManager.GetString("trFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string trIt {
            get {
                return ResourceManager.GetString("trIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radios.
        /// </summary>
        public static string trRadios {
            get {
                return ResourceManager.GetString("trRadios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rations.
        /// </summary>
        public static string trRations {
            get {
                return ResourceManager.GetString("trRations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rge Avail.
        /// </summary>
        public static string trRgeAvail {
            get {
                return ResourceManager.GetString("trRgeAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp Parts.
        /// </summary>
        public static string trSpParts {
            get {
                return ResourceManager.GetString("trSpParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpns.
        /// </summary>
        public static string trWpns {
            get {
                return ResourceManager.GetString("trWpns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniforms.
        /// </summary>
        public static string uniforms {
            get {
                return ResourceManager.GetString("uniforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit/Sqn/Ship:.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Validation Date: .
        /// </summary>
        public static string validityDate {
            get {
                return ResourceManager.GetString("validityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehs.
        /// </summary>
        public static string vehs {
            get {
                return ResourceManager.GetString("vehs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VJTF:.
        /// </summary>
        public static string vjtf {
            get {
                return ResourceManager.GetString("vjtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons Serviceability Rate:.
        /// </summary>
        public static string weaponServRate {
            get {
                return ResourceManager.GetString("weaponServRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpns.
        /// </summary>
        public static string wpns {
            get {
                return ResourceManager.GetString("wpns", resourceCulture);
            }
        }
    }
}
